export const employees = [
  {
    id: 1,
    firstname: "Amit",
    email: "employee1@company.com",
    password: "123",
    taskNumbers: {
      active: 3,
      newtask: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Prepare Sales Report",
        description: "Compile and submit the monthly sales report.",
        date: "2025-08-27",
        category: "Reporting",
        priority: "High",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Client Follow-up",
        description: "Call and follow up with client about pending invoice.",
        date: "2025-08-28",
        category: "Client Management",
        priority: "Medium",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Update CRM",
        description: "Log all recent customer interactions into the CRM system.",
        date: "2025-08-29",
        category: "Data Entry",
        priority: "Low",
        active: false,
        newtask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Weekly Team Meeting",
        description: "Attend and present updates during the weekly team meeting.",
        date: "2025-08-30",
        category: "Meetings",
        priority: "High",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix Data Error",
        description: "Resolve the mismatched entries in the database.",
        date: "2025-09-01",
        category: "Technical",
        priority: "High",
        active: false,
        newtask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 2,
    firstname: "Priya",
    email: "employee2@company.com",
    password: "123",
    taskNumbers: {
      active: 2,
      newtask: 2,
      completed: 2,
      failed: 0,
    },
    tasks: [
      {
        title: "Design Marketing Banner",
        description: "Create banner for the upcoming product launch.",
        date: "2025-08-27",
        category: "Design",
        priority: "High",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Social Media Posts",
        description: "Schedule and upload 3 posts on LinkedIn and Twitter.",
        date: "2025-08-28",
        category: "Marketing",
        priority: "Medium",
        active: false,
        newtask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Product Feedback",
        description: "Collect feedback from 10 customers about new features.",
        date: "2025-08-29",
        category: "Customer Research",
        priority: "High",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Email Campaign",
        description: "Prepare and schedule September email campaign.",
        date: "2025-08-30",
        category: "Marketing",
        priority: "Medium",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Draft Blog Post",
        description: "Write a draft blog on industry trends.",
        date: "2025-09-01",
        category: "Content",
        priority: "Low",
        active: false,
        newtask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    firstname: "Rohit",
    email: "employee3@company.com",
    password: "123",
    taskNumbers: {
      active: 2,
      newtask: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Server Maintenance",
        description: "Run weekly checks and update server patches.",
        date: "2025-08-27",
        category: "IT",
        priority: "High",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Database Backup",
        description: "Perform a full system backup.",
        date: "2025-08-28",
        category: "IT",
        priority: "High",
        active: false,
        newtask: false,
        completed: true,
        failed: false,
      },
      {
        title: "System Monitoring",
        description: "Check for anomalies in system logs.",
        date: "2025-08-29",
        category: "IT",
        priority: "Medium",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Network Audit",
        description: "Audit network usage and submit report.",
        date: "2025-08-30",
        category: "IT",
        priority: "High",
        active: false,
        newtask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Employee Laptop Setup",
        description: "Configure laptops for 2 new employees.",
        date: "2025-09-01",
        category: "Support",
        priority: "Medium",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    firstname: "Neha",
    email: "employee4@company.com",
    password: "123",
    taskNumbers: {
      active: 2,
      newtask: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Recruitment Drive",
        description: "Screen candidates for developer roles.",
        date: "2025-08-27",
        category: "HR",
        priority: "High",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Employee Training",
        description: "Organize training session on cybersecurity.",
        date: "2025-08-28",
        category: "HR",
        priority: "Medium",
        active: false,
        newtask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Policy Update",
        description: "Update leave policy document.",
        date: "2025-08-29",
        category: "Administration",
        priority: "Low",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Payroll Processing",
        description: "Ensure all salaries are processed on time.",
        date: "2025-08-30",
        category: "Finance",
        priority: "High",
        active: false,
        newtask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Organize Event",
        description: "Plan annual cultural event.",
        date: "2025-09-01",
        category: "HR",
        priority: "Medium",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    firstname: "Arjun",
    email: "employee5@company.com",
    password: "123",
    taskNumbers: {
      active: 2,
      newtask: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Customer Onboarding",
        description: "Assist new customer with account setup.",
        date: "2025-08-27",
        category: "Support",
        priority: "High",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Resolve Ticket #123",
        description: "Fix reported issue on payment gateway.",
        date: "2025-08-28",
        category: "Support",
        priority: "High",
        active: false,
        newtask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Knowledge Base Update",
        description: "Update FAQ section with new solutions.",
        date: "2025-08-29",
        category: "Documentation",
        priority: "Low",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Check Bug Reports",
        description: "Review open bug reports and assign priorities.",
        date: "2025-08-30",
        category: "Support",
        priority: "Medium",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Customer Training",
        description: "Host webinar to train customers on product usage.",
        date: "2025-09-01",
        category: "Training",
        priority: "Medium",
        active: false,
        newtask: false,
        completed: false,
        failed: true,
      },
    ],
  },
];

export const admin = [
  {
    id: 101,
    firstname: "Sanjay",
    email: "admin@company.com",
    password: "123",
  },
];